import Link from "next/link";
import { CONTACT_EMAIL } from "@/config/site";

export const metadata = {
  title: "Terms of Service - PathPilot",
  description: "The terms that govern your use of PathPilot.",
};

const LAST_UPDATED = "August 18, 2026";
const GOVERNING_LAW = "the State of California, United States";

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-text px-4 py-16 sm:px-6 md:py-24">
      <div className="mb-12">
        <h1 className="mb-3 font-display text-2xl font-[400] tracking-[-0.015em] text-ink md:text-3xl">
          Terms of Service
        </h1>
        <p className="text-sm text-ink-muted">
          Last updated: {LAST_UPDATED}
        </p>
      </div>

      <div className="space-y-12 text-base leading-relaxed text-ink">
        <section>
          <p>
            These Terms of Service (&ldquo;Terms&rdquo;) govern your use of
            PathPilot, an independent project built and operated by Javier
            Padilla (&ldquo;we,&rdquo; &ldquo;us&rdquo;). By creating an
            account or using PathPilot, you agree to these Terms. If you
            don&apos;t agree, please don&apos;t use the service.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            1. What PathPilot is
          </h2>
          <p className="text-ink-muted">
            PathPilot analyzes your CV and questionnaire responses using an
            AI model to suggest possible career paths, highlight strengths,
            and propose a short-term action plan. It is a decision-support
            tool, not a career counseling service, recruiter, or employment
            agency.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            2. Eligibility
          </h2>
          <p className="text-ink-muted">
            You must be at least 16 years old to create an account. By using
            PathPilot, you confirm that you meet this requirement and that
            the information you provide is accurate.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            3. Your account
          </h2>
          <p className="text-ink-muted">
            You&apos;re responsible for keeping your login credentials secure
            and for all activity that happens under your account. Let us
            know right away if you suspect unauthorized access.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            4. Acceptable use
          </h2>
          <p className="text-ink-muted mb-2">You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1.5 text-ink-muted">
            <li>Upload a CV or personal information belonging to someone else without their consent</li>
            <li>Use PathPilot for any unlawful purpose</li>
            <li>Attempt to interfere with, overload, or reverse-engineer the service</li>
            <li>Attempt to extract, scrape, or resell analysis output at scale</li>
            <li>Use automated tools to create accounts or submit requests</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            5. AI-generated content: please read this one
          </h2>
          <p className="text-ink-muted">
            Your analysis is generated by an AI model based on the
            information you provide. It is <span className="text-ink">not</span>{" "}
            professional career, legal, financial, or immigration advice, and
            it may be incomplete, generic, or occasionally wrong. Career
            paths, fit scores, and action plans are directional suggestions,
            not guarantees of employability, salary, or outcome. Use your own
            judgment, and consult a qualified professional for decisions that
            matter.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            6. Intellectual property
          </h2>
          <p className="text-ink-muted">
            You keep all rights to the CV and information you upload. By
            submitting it, you grant us a limited license to process it
            solely to generate and store your analysis. PathPilot&apos;s
            branding, design, and underlying code belong to us and may not be
            copied or reused without permission.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            7. Termination
          </h2>
          <p className="text-ink-muted">
            You may stop using PathPilot and request account deletion at any
            time. We may suspend or terminate accounts that violate these
            Terms, misuse the service, or pose a security risk.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            8. No warranty
          </h2>
          <p className="text-ink-muted">
            PathPilot is provided &ldquo;as is&rdquo; and &ldquo;as
            available,&rdquo; without warranties of any kind, express or
            implied. We don&apos;t guarantee the service will be
            uninterrupted, error-free, or that any analysis will lead to a
            particular outcome.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            9. Limitation of liability
          </h2>
          <p className="text-ink-muted">
            To the fullest extent permitted by law, PathPilot and its
            operator are not liable for any indirect, incidental, or
            consequential damages arising from your use of the service,
            including career or employment decisions made based on an
            analysis.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            10. Governing law
          </h2>
          <p className="text-ink-muted">
            These Terms are governed by the laws of {GOVERNING_LAW}, without
            regard to conflict-of-law principles.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            11. Changes to these terms
          </h2>
          <p className="text-ink-muted">
            We may update these Terms occasionally. We&apos;ll update the
            date above when we do. Continuing to use PathPilot after a change
            means you accept the revised Terms.
          </p>
        </section>

        <section>
          <h2 className="mb-3 font-display text-xl font-[420] text-ink">
            12. Contact us
          </h2>
          <p className="text-ink-muted">
            Questions about these Terms? Reach out at{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-forest underline decoration-forest/40 underline-offset-4 hover:decoration-forest">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </section>
      </div>

      <div className="mt-16 border-t border-contour pt-8">
        <Link
          href="/privacy"
          className="rounded-control text-base font-medium text-forest underline decoration-forest/40 underline-offset-4 hover:decoration-forest"
        >
          Read the Privacy Policy
        </Link>
      </div>
    </div>
  );
}
